### ISSUE TITLE
@ModelField is applicable to ElementType.METHOD ...

### ISSUE THREAD

**Issue by zmitrok** [ralscha/extclassgenerator#28]
... but the class generator does not scan methods for annotations, only types and fields. Not sure which needs to be updated the ModelField annotation or the class generator ;-)

**Comment by ralscha** [comment]
It is supported for interfaces
https://github.com/ralscha/extclassgenerator/issues/1

```
@Model
public interface User {

	@ModelField
	UUID getId();

	@NotEmpty
	@Email
	@Size(max = 128)
	String getEmail();
}
```

**Comment by zmitrok** [comment]
Is there any reason not to support it for classes? It could be used in conjunction with Jackson's @JsonProperty, @JsonGetter/Setter annotations on methods when there are no backing fields. Currently I use @ModelFields({...}) on the DTO type, but it would be nice to have Jackson and extclassgenerator annotations grouped together in code visually.

**Comment by ralscha** [comment]
I added some code to support @ModelField on methods. 
Can you try 1.0.7-SNAPSHOT?

**Comment by zmitrok** [comment]
Tried 1.0.7-SNAPSHOT. Seems to work fine, and a nice side effect is that the model field type is auto-detected from the method return type and I don't have to specify it in the @ModelField annotation.

**Comment by ralscha** [comment]
1.0.7 released. Thanks a lot for the donation. I appreciate it
