### ISSUE TITLE
Model properties picked up from methods annotations are output in random order

### ISSUE THREAD

**Issue by zmitrok** [ralscha/extclassgenerator#29]
This is related to #28 . Sorry it took me some time to detect this.

**Comment by ralscha** [comment]
They are written in the order that class.getDeclaredMethods returns. 
Looks like you cannot get the order they appear with this method. You could maybe do this with some bytecode magic.
http://stackoverflow.com/questions/6996910/is-possible-getmethods-in-order-using-reflections
or we add a ```order``` attribute to the ModelField annotation

But the question is what problem do we try to solve.
Ext JS does not care about the order of the fields.

**Comment by zmitrok** [comment]
ExtJS does not care about the order of the fields, of course, so it isn't really about ExtJS.

In my case the Javascript models generated are checked into the revision control system. Running the model generation step multiple times produces slightly different results now that the order of the methods is random. These changes show up in the IDE and I have to either revert them or commit them with other changes, and the next time the project is compiled the model files might be marked as changed again.

I guess for the last few years I relied on the fact that extclassgenerator was deterministic in the way it worked before, and now this nice side effect is gone and I have nobody to blame for it but myself :-)

I guess one simple solution to this problem would be to use ordered collections (TreeSet?) in the ModelBean and related classes.

**Comment by ralscha** [comment]
I see the problem. I hate that too when a code generator generates different code every time he runs.

It's interesting that there never was a problem with class.getDeclardFields. According to the javadoc this method returns the fields in any order.
"The elements in the array returned are not sorted and are not in any particular order"

Using TreeSet would solve the problem, but also change all my generated models. 
My suggestion is that we only add a sort step to the code that handles the methods.

**Comment by zmitrok** [comment]
Field order is important for object construction, so I guess that even though the order is not guaranteed, Class.getDeclaredFields simply returns a copy of fields arranged in the order of their initialization and declaration.

Sorting method-based model properties would work just fine, I agree.

**Comment by ralscha** [comment]
1.0.8-SNAPSHOT is ready for testing. If okay I will release a new version.

**Comment by zmitrok** [comment]
So far so good. I can see all method-based model properties sorted by name.
