### ISSUE TITLE
ClassNotFound

### ISSUE THREAD

**Issue by GuoRuiLv** [ralscha/extclassgenerator#32]
Hi,
I use the  ModelAnnotationProcessor within Intellij IDEA using the  ["gradle-apt-plugin"](https://github.com/tbroyer/gradle-apt-plugin),  the console print some error message:

```
Warning: No SupportedSourceVersion annotation found on ch.rasc.extclassgenerator.ModelAnnotationProcessor, returning RELEASE_6.
Warning: 来自注释处理程序 'ch.rasc.extclassgenerator.ModelAnnotationProcessor' 的受支持 source 版本 'RELEASE_6' 低于 -source '1.8'
注: Running ModelAnnotationProcessor
Error com.jdsoft.studio.Author
Error: com.jdsoft.studio.Book
Error: com.jdsoft.studio.model.Project
Error: com.jdsoft.studio.model.SampleProject
注: Running ModelAnnotationProcessor
Warning: 以下选项未被任何处理程序识别: '[createBaseAndSubclass, surroundApiWithQuotes]'.

```
Then i debug the gradle,i found the inner exception is ClassNotFoundException,see pickure below:
![classnotfoundexception](https://user-images.githubusercontent.com/1725996/31603877-236588f0-b294-11e7-8eab-c8f1869572c5.png)
It seems like the classloader can't find the my Model class ,how shoud i handle this problem?
Thanks!

**Comment by lugreen** [comment]
Hi,
I also posted a issue  on [gradle-apt-plugin ](https://github.com/tbroyer/gradle-apt-plugin/issues/63).
To thre plugin author's mind, it seems that  the problem  casuse by the  annotated class is not  in the same "classpath" as the annotation processor.

**Comment by ralscha** [comment]
Hi
The problem is that when I wrote this apt I didn't use the proper apt methods. 
For example I load the classes with Class.forName which is not something you should do in a apt.
It does work with Maven so never bothered to rewrite it.

To be a proper apt it needs a complete rewrite and depend solely on the javax.lang.model api.
Like the other apt I wrote (https://github.com/ralscha/constgen and https://github.com/ralscha/bsoncodec-apt)

**Comment by lugreen** [comment]
Hi,
Thanks for your advice. I will try it.

**Comment by ralscha** [comment]
I started a new project: https://github.com/ralscha/extclassgenerator-apt
It currently does not compile. There are a few tricky parts. The APT should not use Reflection instead it should use the javax.lang.model API

**Comment by lugreen** [comment]
Hi,
Thanks very much.
